### ISSUE TITLE
Remove of IpcRendererEvent.senderId breaks REMOTE_RENDERER_CALLBACK with Electron 28

### ISSUE THREAD

**Issue by pbi-qfs** [electron/remote#170]
The change from https://github.com/electron/electron/commit/5078cae86181735bc50684fd56d50488bc6766f5 has landed in Electron 28beta.

This change breaks the security check in https://github.com/electron/remote/blob/c258862b1a97dde98896ded015ced5baf87c485a/src/renderer/remote.ts#L314-L317 leading to the console error `REMOTE_RENDERER_CALLBACK sent by unexpected WebContents (undefined)` and no callback execution.

Would it be enough to revert https://github.com/electron/remote/commit/740ed4ebb86d7701356271e764b221bad3822765 ? or at least accept `undefined` as alternative to support Electron 28+? Maybe this is not so bad anymore, since according to https://github.com/electron/electron/blob/6697042c0ab61ac55e91251427a131792de0358e/docs/breaking-changes.md?plain=1#L17C29-L17C29 the ipcRenderer shouldn't be easily leaked in future anymore...

**Comment by pbi-qfs** [comment]
Fixed with #171

**Comment by stephanebouget** [comment]
I still have this issue with Electron 28 or 29 and electron-remote 2.1.2 
it's OK with Electron 27.x

**Comment by astoilkov** [comment]
I created a new issue because after this was completed there seems to be reappearance of the issue — https://github.com/electron/remote/issues/182.
